---
title: "Análise da base RAIS"
description: |
  Essa análise teve como objetivo analisar os salários na base RAIS. Esse projeto foi feito na Semana Data Science na prático do Curso-R.
author:
  - name: Mariana Costa
date: 2021-12-07
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Nesse relatório estamos interessados em saber em responder a pergunta:

"Quanto ganha um ciestista de dados?"

Para isso, vamos acessar a base da RAIS.

# Acessando os dados da RAIS

Vamos utilizar [o datalake da iniciativa base dos dados](https://basedosdados.org).


```{r message=FALSE, warning=FALSE}

library(bigrquery)
library(dplyr)
```

Abaixo está o código que carrega as primeira 5 linhas da tabela de microdados.

```{r message=FALSE, warning=FALSE}

bigrquery::bq_auth("marianascosta77@gmail.com")

conexao <- dbConnect (
  bigquery(),
  project = "basedosdados",
  dataset = "br_me_rais",
  billing = "sodium-replica-334503"
)

primeiras_cinco_linhas <- collect(head(select(tbl(conexao, "microdados_vinculos"), everything()), 5))

knitr::kable(primeiras_cinco_linhas)
```

